
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: lanchonete
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lanchonete
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  tests:
    image: maven:3.8.4-openjdk-8
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    # Instala o psql e roda o script de testes
    command: /bin/bash -c "apt-get update && apt-get install -y postgresql-client && ./scripts/run_tests.sh"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lanchonete
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "5005:5005"
